
  CREATE TABLE "WORKOUT"."STOCK" 
   (	"STOCK_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"STOCKCODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STOCKNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("STOCK_ID")
);
  CREATE TABLE "WORKOUT"."STOCK_DAILY_RECORD" 
   (	"RECORD_ID" integer NOT NULL ENABLE, 
	"PRICE_OPEN" FLOAT , 
	"PRICE_CLOSE" FLOAT , 
	"PRICE_CHANGE"FLOAT , 
	"VOLUME" LONG , 
	dateAdded TIMESTAMP , 
	"STOCK_ID" integer, 
	 PRIMARY KEY ("RECORD_ID"),
CONSTRAINT fk_supplier FOREIGN KEY ("STOCK_ID")
    REFERENCES STOCK

);
CREATE SEQUENCE STOCK_sequence
START WITH 1
INCREMENT BY 1;
